server:
  port: 8081
spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
paze:
  base-url: https://app-demo.paze.eu/api/v1
  auth-token: cAmmvalAikARkB81fgxgMtnMbEdNbuWa
